version: 0.0
os: linux
files:
  - source: /app.jar
    destination: /home/ubuntu/app/
  - source: /ttasup.service
    destination: /home/ubuntu/app/
hooks:
  # 새 버전을 설치하기 전 단계
  BeforeInstall:
    # 1. 기존 앱 중지 (systemd로 제어)
    - location: scripts/stop.sh
      timeout: 60
      runas: root
    # 2. JDK 17 설치 및 디렉토리 (멱등성 유지)
    - location: scripts/setup.sh
      timeout: 300
      runas: root
  # 새 버전 설치가 끝난 후 단계
  AfterInstall:
    # 3. 파일 권한 설정 및 systemd 서비스 등록
    - location: scripts/register_service.sh
      timeout: 300
      runas: root
  # 배포의 마지막 단계
  ApplicationStart:
    # 4. systemd를 통해 새 버전 앱 시작
    - location: scripts/start.sh
      timeout: 60
      runas: root