name: Deploy Ttasup Spring Boot server to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 # JDK 17 버전 사용
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        working-directory: family

      - name: Debug built JAR
        run: ls -alh family/build/libs

      - name: Clean up old artifact directory
        run: |
          rm -rf codedeploy_artifact
          rm -f deploy.zip

      - name: Make scripts executable
        run: chmod +x deploy/scripts/*.sh

      - name: Prepare deployment package
        run: |
          mkdir codedeploy_artifact
          cp family/build/libs/family-0.0.1-SNAPSHOT.jar codedeploy_artifact/app.jar
          cp appspec.yml codedeploy_artifact/
          cp -r deploy/scripts codedeploy_artifact/
          cd codedeploy_artifact
          zip -r ../deploy.zip ./*

#     application.yml 추가 되면 주석 해제

#      - name: Create application.yml
#        run: |
#          echo "${{ secrets.APPLICATION_YML_BASE64 }}" | base64 --decode > src/main/resources/application.yml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy/deploy.zip

      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name ttasup-dev-cicd \
            --deployment-group-name ttasup-dev-cicd-deploygroup \
            --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},key=deploy/deploy.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE